feat: Avoid bpf_features conflict declaration
It would fail to build `feat_bpfel.o`:

```bash
/root/bpfsnoop/bpf/feature.c:9:1: error: use of 'bpf_features' with tag type that does not match previous declaration
    9 | struct bpf_features {
      | ^
/root/bpfsnoop/bpf/headers/vmlinux.h:13305:6: note: previous use is here
 13305 | enum bpf_features {
       |      ^
1 error generated.
Error: compile: exit status 1
exit status 1
make: *** [Makefile:42: internal/bpf/feat_bpfel.o] Error 1
```

Rename `bpf_features` to `__features`.

Signed-off-by: Leon Hwang <leon.hwang@linux.dev>